In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mock_data.csv")

In [3]:
pd.set_option("display.max_columns",100)

In [4]:
df.head()

,Crash Death Count,Crash Severity,Crash Time,Crash Total Injury Count,Crash Year,Day of Week,Highway Number,Highway System,Latitude,Light Condition,Longitude,Surface Condition,Surface Type,Weather Condition,Vehicle Body Style,Vehicle Damage Rating 1 - Severity,Vehicle Damage Rating 2 - Severity,Vehicle Make,Vehicle Model Name,Vehicle Model Year,Citation,Person Age,Person Alcohol Result,Person Drug Test Result,Person Gender,Person Injury Severity,Person Type
0,0,N - NOT INJURED,1111,0,2018,MONDAY,No Data,No Data,30.20098162,1 - DAYLIGHT,-97.87090786,1 - DRY,No Data,1 - CLEAR,VN - VAN,3 - DAMAGED 3,No Data,HONDA,ODYSSEY (HONDA),2005,No Data,34,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
1,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",7 - DAMAGED 7 HIGHEST,No Data,HONDA,CIVIC (HONDA),2013,E16001834,49,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
2,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,22,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
3,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,48,No Data,No Data,2 - FEMALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT
4,0,N - NOT INJURED,728,0,2018,MONDAY,734,FARM TO MARKET,30.40533278,"2 - DARK, NOT LIGHTED",-97.66431513,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",3 - DAMAGED 3,No Data,CHRYSLER,300 (CHRYSLER),2006,No Data,21,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER

In [5]:
df = df.reset_index()

In [6]:
newdf= df.rename(columns= {'index': "ID"})
newdf

,ID,Crash Death Count,Crash Severity,Crash Time,Crash Total Injury Count,Crash Year,Day of Week,Highway Number,Highway System,Latitude,Light Condition,Longitude,Surface Condition,Surface Type,Weather Condition,Vehicle Body Style,Vehicle Damage Rating 1 - Severity,Vehicle Damage Rating 2 - Severity,Vehicle Make,Vehicle Model Name,Vehicle Model Year,Citation,Person Age,Person Alcohol Result,Person Drug Test Result,Person Gender,Person Injury Severity,Person Type
0,0,0,N - NOT INJURED,1111,0,2018,MONDAY,No Data,No Data,30.20098162,1 - DAYLIGHT,-97.87090786,1 - DRY,No Data,1 - CLEAR,VN - VAN,3 - DAMAGED 3,No Data,HONDA,ODYSSEY (HONDA),2005,No Data,34,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
1,1,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",7 - DAMAGED 7 HIGHEST,No Data,HONDA,CIVIC (HONDA),2013,E16001834,49,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
2,2,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,22,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
3,3,0,N - NOT INJURED,36,0,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,48,No Data,No Data,2 - FEMALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT
4,4,0,N - NOT INJURED,728,0,2018,MONDAY,734,FARM TO MARKET,30.40533278,"2 - DARK, NOT LIGHTED",-97.66431513,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",3 - DAMAGED 3,No Data,CHRYSLER,300 (CHRYSLER),2006,No Data,21,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119098,119098,0,C - POSSIBLE INJURY,1015,1,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,LEXUS,ES 300 (LEXUS),2000,No Data,94,No Data,No Data,1 - MALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT
119099,119099,0,C - POSSIBLE INJURY,1015,1,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",5 - DAMAGED 5,No Data,TOYOTA,CAMRY (TOYOTA),2011,No Data,39,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119100,119100,0,N - NOT INJURED,1118,0,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,HYUNDAI,SONATA (HYUNDAI),2011,"E17305749, E17305749",31,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119101,119101,0,N - NOT INJURED,1118,0,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,FORD,ESCAPE (FORD),2013,No Data,32,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119102,119102,0,N - NOT INJURED,1118,0,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,FORD,ESCAPE (FORD),2013,No Data,0,No Data,No Data,2 - FEMALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT

In [7]:
internal_df= newdf[['ID','Crash Time', 'Crash Death Count', 'Crash Severity', 'Crash Total Injury Count', 'Crash Year', 'Vehicle Body Style', 'Vehicle Damage Rating 1 - Severity','Vehicle Damage Rating 2 - Severity', 'Vehicle Make', 'Vehicle Model Name', 'Vehicle Model Year', 'Citation', 'Person Age', 'Person Alcohol Result', 'Person Drug Test Result', 'Person Gender', 'Person Injury Severity' , 'Person Type']]
internal_df

,ID,Crash Time,Crash Death Count,Crash Severity,Crash Total Injury Count,Crash Year,Vehicle Body Style,Vehicle Damage Rating 1 - Severity,Vehicle Damage Rating 2 - Severity,Vehicle Make,Vehicle Model Name,Vehicle Model Year,Citation,Person Age,Person Alcohol Result,Person Drug Test Result,Person Gender,Person Injury Severity,Person Type
0,0,1111,0,N - NOT INJURED,0,2018,VN - VAN,3 - DAMAGED 3,No Data,HONDA,ODYSSEY (HONDA),2005,No Data,34,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
1,1,36,0,N - NOT INJURED,0,2018,"P4 - PASSENGER CAR, 4-DOOR",7 - DAMAGED 7 HIGHEST,No Data,HONDA,CIVIC (HONDA),2013,E16001834,49,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
2,2,36,0,N - NOT INJURED,0,2018,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,22,No Data,97 - NOT APPLICABLE,2 - FEMALE,N - NOT INJURED,1 - DRIVER
3,3,36,0,N - NOT INJURED,0,2018,"P4 - PASSENGER CAR, 4-DOOR",6 - DAMAGED 6,No Data,HYUNDAI,SANTA FE (HYUNDAI),2011,No Data,48,No Data,No Data,2 - FEMALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT
4,4,728,0,N - NOT INJURED,0,2018,"P4 - PASSENGER CAR, 4-DOOR",3 - DAMAGED 3,No Data,CHRYSLER,300 (CHRYSLER),2006,No Data,21,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119098,119098,1015,0,C - POSSIBLE INJURY,1,2020,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,LEXUS,ES 300 (LEXUS),2000,No Data,94,No Data,No Data,1 - MALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT
119099,119099,1015,0,C - POSSIBLE INJURY,1,2020,"P4 - PASSENGER CAR, 4-DOOR",5 - DAMAGED 5,No Data,TOYOTA,CAMRY (TOYOTA),2011,No Data,39,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119100,119100,1118,0,N - NOT INJURED,0,2020,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,HYUNDAI,SONATA (HYUNDAI),2011,"E17305749, E17305749",31,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119101,119101,1118,0,N - NOT INJURED,0,2020,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,FORD,ESCAPE (FORD),2013,No Data,32,No Data,97 - NOT APPLICABLE,1 - MALE,N - NOT INJURED,1 - DRIVER
119102,119102,1118,0,N - NOT INJURED,0,2020,"P4 - PASSENGER CAR, 4-DOOR",4 - DAMAGED 4,No Data,FORD,ESCAPE (FORD),2013,No Data,0,No Data,No Data,2 - FEMALE,N - NOT INJURED,2 - PASSENGER/OCCUPANT

In [8]:
external_df= newdf[['ID', 'Crash Year', 'Day of Week', 'Highway Number', 'Highway System', 'Latitude', 'Light Condition', 'Longitude', 'Surface Condition', 'Surface Type', 'Weather Condition']]
external_df

,ID,Crash Year,Day of Week,Highway Number,Highway System,Latitude,Light Condition,Longitude,Surface Condition,Surface Type,Weather Condition
0,0,2018,MONDAY,No Data,No Data,30.20098162,1 - DAYLIGHT,-97.87090786,1 - DRY,No Data,1 - CLEAR
1,1,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR
2,2,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR
3,3,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,No Data,1 - CLEAR
4,4,2018,MONDAY,734,FARM TO MARKET,30.40533278,"2 - DARK, NOT LIGHTED",-97.66431513,1 - DRY,No Data,2 - CLOUDY
...,...,...,...,...,...,...,...,...,...,...,...
119098,119098,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,No Data,2 - CLOUDY
119099,119099,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,No Data,2 - CLOUDY
119100,119100,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY
119101,119101,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY
119102,119102,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,No Data,2 - CLOUDY

In [13]:
external_df = external_df.drop(columns = "Surface Type")

In [14]:
external_df

,ID,Crash Year,Day of Week,Highway Number,Highway System,Latitude,Light Condition,Longitude,Surface Condition,Weather Condition
0,0,2018,MONDAY,No Data,No Data,30.20098162,1 - DAYLIGHT,-97.87090786,1 - DRY,1 - CLEAR
1,1,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,1 - CLEAR
2,2,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,1 - CLEAR
3,3,2018,MONDAY,734,FARM TO MARKET,30.36856269,"3 - DARK, LIGHTED",-97.61329002,1 - DRY,1 - CLEAR
4,4,2018,MONDAY,734,FARM TO MARKET,30.40533278,"2 - DARK, NOT LIGHTED",-97.66431513,1 - DRY,2 - CLOUDY
...,...,...,...,...,...,...,...,...,...,...
119098,119098,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,2 - CLOUDY
119099,119099,2020,TUESDAY,No Data,No Data,30.35237476,1 - DAYLIGHT,-97.75114246,1 - DRY,2 - CLOUDY
119100,119100,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,2 - CLOUDY
119101,119101,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,2 - CLOUDY
119102,119102,2020,TUESDAY,No Data,No Data,30.28755477,1 - DAYLIGHT,-97.70702247,1 - DRY,2 - CLOUDY

In [15]:
df.to_csv("crash_data.csv")

In [16]:
import csv_to_sqlite 

# all the usual options are supported
options = csv_to_sqlite.CsvOptions(typing_style="full", encoding="windows-1250") 
input_files = ["crash_data.csv] # pass in a list of CSV files
csv_to_sqlite.write_csv(input_files, "output.sqlite", options)

SyntaxError: EOL while scanning string literal (<ipython-input-16-3ccf6fc9dabc>, line 5)